version: '3.8'

services:
  angular-app:
    build: .
    ports:
      - "4200:80"
    depends_on:
      - json-server
    networks:
      - app-network

  json-server:
    build:
      context: ./json-server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
